# Welcome to Jekyll!
#
title: Alberto Moyano
email: alberto.alejandro.moyano@gmail.com
author: Alberto Moyano

# DO NOT CHANGE THE LINE OF THIS FILE without editing .circleci/circle_urls.sh
# baseurl: "/blog-alberto" # the subpath of your site, e.g. /blog

# Social (First three Required)
repo: "https://github.com/albertomoyano" # repositorio general del autor
github_user: "albertomoyano"

# Optional
linkedin: albertomoyano
google-analytics: G-B24LS8J7J2
logo: "assets/img/favicon.png"
color: "#DC143C" # color de la cabecera

# Build settings
markdown: kramdown

tag_search_endpoint: https://es.wikipedia.org/wiki/
tag_color: info # danger, success, warning, primary, info, secondary

accentColor: red # purple, green, etc.
themeColor: red # purple, green, blue, orange, purple, grey
fixedNav: 'false' # true or false

permalink: /:year/:title/
markdown: kramdown
exclude: [_site, CHANGELOG.md, LICENSE, README.md, vendor]

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path

# Defaults
defaults:
  - scope:
      path: "_docs"
      type: "docs"
    values:
      layout: page
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: "posts"
      type: "posts"
    values:
      layout: "post"

